// table schema generated by introspection
import { sql } from "drizzle-orm";
import {
  sqliteTable,
  uniqueIndex,
  integer,
  text,
} from "drizzle-orm/sqlite-core";

const getCurrentUnixTimestamp = () => Math.floor(Date.now() / 1000);

export const usersTable = sqliteTable(
  "users_table",
  {
    id: integer().primaryKey({ autoIncrement: true }).notNull(),
    email: text().notNull(),
    refreshToken: text(),
    password: text(),
  },
  (table) => {
    return {
      emailUnique: uniqueIndex("users_table_email_unique").on(table.email),
    };
  },
);

export const otpTable = sqliteTable(
  "otp_table",
  {
    id: integer().primaryKey({ autoIncrement: true }).notNull(),
    email: text().notNull(),
    phone: text(),
    status: text({ enum: ["pending", "verified"] })
      .notNull()
      .default("pending"),
    otp: text().notNull(),
    updatedAt: integer()
      .$defaultFn(() => getCurrentUnixTimestamp())
      .$onUpdateFn(() => getCurrentUnixTimestamp()),
    createdAt: integer().$defaultFn(() => getCurrentUnixTimestamp()),
  },
  (table) => {
    return {
      emailUnique: uniqueIndex("otp_table_email_unique").on(table.email),
    };
  },
);
